### ISSUE TITLE
Reducing Laravel Requirement?

### ISSUE THREAD

**Issue by OwenMelbz** [stuyam/laravel-kickbox-validator#2]
Hey,

We're building a site on [statamic](https://statamic.com/) and always jump to your package for kickbox integration.

However Statamic runs laravel 5.1

The composer json file requires 5.2

We've tested it with 5.1 and cannot see any 5.2 specific code - so we were wondering if you'd be willing to try reduce the minimum required version from 5.2 to 5.1?

thanks :)

**Comment by stuyam** [comment]
@OwenMelbz I would love to, didn't even realize it was set that high, it should work on all 5 versions of Laravel. Let me do that now and thanks for using the packages 😄

**Comment by stuyam** [comment]
Published in release 1.0.2 👍
